### ISSUE TITLE
请问下如何设置CUDA_VISIBLE_DEVICES环境变量？

### ISSUE THREAD

**Issue by guotong1988** [tobegit3hub/distributed_tensorflow#2]
有没有些参考资料？多谢@tobegit3hub

**Comment by tobegit3hub** [comment]
You can refer to this QA in stackoverflow http://stackoverflow.com/questions/37893755/tensorflow-set-cuda-visible-devices-within-jupyter

Just follow the instructions in README.md and google about the detail about this. It's really not an issue about this project so please use Github properly.
